-- MySQL Script generated by MySQL Workbench
-- Sun 03 Sep 2017 02:21:59 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_template_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_template_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_template_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_template_service` ;

-- -----------------------------------------------------
-- Table `ulbora_template_service`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_template_service`.`template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT 'default',
  `application` VARCHAR(10) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
